export default function RightMenu() {
  return (
    <div
      className="
        absolute
        top-[222px]
        md:top-[120px]
        lg:top-[160px]
        xl:top-[222px]
        left-[1239px]
        md:left-[660px]
        lg:left-[860px]
        xl:left-[1239px]
        w-[151px]
        md:w-[100px]
        lg:w-[125px]
        xl:w-[151px]
        h-[153px]
        md:h-[110px]
        lg:h-[130px]
        xl:h-[153px]
        flex
        flex-col
        items-end
        gap-[12px]
        md:gap-[8px]
        lg:gap-[10px]
        xl:gap-[12px]
      "
    >
      {/* Our Projects + */}
      <div className="flex items-center justify-end gap-[2px] w-full">
        <div
          className="
            text-[18px]
            md:text-[12px]
            lg:text-[15px]
            xl:text-[18px]
            leading-[21px]
            md:leading-[14px]
            lg:leading-[18px]
            xl:leading-[21px]
            font-medium
            uppercase
            tracking-[0.01em]
            text-[#1E1E1E]
          "
        >
          Our Projects
        </div>
        <div
          className="
            text-[24px]
            md:text-[16px]
            lg:text-[20px]
            xl:text-[24px]
            leading-[29px]
            md:leading-[20px]
            lg:leading-[24px]
            xl:leading-[29px]
            font-medium
            uppercase
            text-[#BB9CFB]
          "
        >
          +
        </div>
      </div>

      {/* Design */}
      <div
        className="
          w-[71px]
          md:w-[50px]
          lg:w-[60px]
          xl:w-[71px]
          text-[18px]
          md:text-[12px]
          lg:text-[15px]
          xl:text-[18px]
          leading-[21px]
          md:leading-[14px]
          lg:leading-[18px]
          xl:leading-[21px]
          font-medium
          uppercase
          tracking-[0.01em]
          text-[rgba(30,30,30,0.5)]
          text-right
        "
      >
        Design
      </div>

      {/* Development */}
      <div
        className="
          w-[133px]
          md:w-[90px]
          lg:w-[110px]
          xl:w-[133px]
          text-[18px]
          md:text-[12px]
          lg:text-[15px]
          xl:text-[18px]
          leading-[21px]
          md:leading-[14px]
          lg:leading-[18px]
          xl:leading-[21px]
          font-medium
          uppercase
          tracking-[0.01em]
          text-[rgba(30,30,30,0.5)]
          text-right
        "
      >
        Development
      </div>

      {/* About Us */}
      <div
        className="
          w-[91px]
          md:w-[62px]
          lg:w-[75px]
          xl:w-[91px]
          text-[18px]
          md:text-[12px]
          lg:text-[15px]
          xl:text-[18px]
          leading-[21px]
          md:leading-[14px]
          lg:leading-[18px]
          xl:leading-[21px]
          font-medium
          uppercase
          tracking-[0.01em]
          text-[rgba(30,30,30,0.5)]
          text-right
        "
      >
        About Us
      </div>

      {/* Get in Touch */}
      <div
        className="
          w-[129px]
          md:w-[88px]
          lg:w-[106px]
          xl:w-[129px]
          text-[18px]
          md:text-[12px]
          lg:text-[15px]
          xl:text-[18px]
          leading-[21px]
          md:leading-[14px]
          lg:leading-[18px]
          xl:leading-[21px]
          font-medium
          uppercase
          tracking-[0.01em]
          text-[rgba(30,30,30,0.5)]
          text-right
        "
      >
        Get in Touch
      </div>
    </div>
  );
}